# Generated by Django 4.1.1 on 2023-11-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_usermanager_alter_user_managers_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
